int ps1_prob2Disc(int a,int b,int c);
void ps1_prob4PrintDay(int n);
int ps1_prob9FindNumOfDigits(int n);
void ps1_prob9IntToArray(int n,int *arr);
void ps1_prob1();
void ps1_prob2();
void ps1_prob3();
void ps1_prob4();
void ps1_prob5(int,int);
void ps1_prob6();
void ps1_prob7();
void ps1_prob8();
void ps1_prob9();
void ps1_prob10();
